template_path: ec2/internet_gateway.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  internet_gateways:
    - name: mainvpc
      vpc_id: !stack_output networkhub/ec2/vpc.yaml::mainvpc
      tags:
        Name: mainvpc
        Project: {{ stack_group_config.project_code }}

stack_tags:
  Name: networkhub-internetgateway