template_path: ec2/network_acl.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  nacls:
    - name: publicnacl
      vpc_id: !stack_output networkhub/ec2/vpc.yaml::mainvpc
      tags:
        Name: Public-NACL
        Project: {{ stack_group_config.project_code }}
      nacl_entries:
        - rule_number: 10100
          rule_action: allow
          direction: ingress
          protocol: -1
          cidr_block: {{ var.network_range }}
        - rule_number: 10106
          rule_action: allow
          direction: ingress
          protocol: -1
          ipv6_cidr_block: !stack_output networkhub/ec2/vpc.yaml::mainvpcCidrBlockIPv6
        - rule_number: 10110
          rule_action: allow
          direction: ingress
          protocol: -1
          cidr_block: {{ var.subnet_cidr_block.office.hq }}
        - rule_number: 10200
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 6
          port_range:
            from: 1024
            to: 65535
        - rule_number: 10206
          rule_action: allow
          direction: ingress
          ipv6_cidr_block: "::/0"
          protocol: 6
          port_range:
            from: 1024
            to: 65535
        - rule_number: 10300
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 17
          port_range:
            from: 1024
            to: 65535
        - rule_number: 10306
          rule_action: allow
          direction: ingress
          ipv6_cidr_block: "::/0"
          protocol: 17
          port_range:
            from: 1024
            to: 65535
        - rule_number: 30100
          rule_action: allow
          direction: egress
          protocol: -1
          cidr_block: 0.0.0.0/0
        - rule_number: 30106
          rule_action: allow
          direction: egress
          protocol: -1
          ipv6_cidr_block: "::/0"
    - name: privatenacl
      vpc_id: !stack_output networkhub/ec2/vpc.yaml::mainvpc
      tags:
        Name: Private-NACL
        Project: {{ stack_group_config.project_code }}
      nacl_entries:
        - rule_number: 10100
          rule_action: allow
          direction: ingress
          protocol: -1
          cidr_block: {{ var.subnet_cidr_block.network_hub.vpc }}
        - rule_number: 10106
          rule_action: allow
          direction: ingress
          protocol: -1
          ipv6_cidr_block: !stack_output networkhub/ec2/vpc.yaml::mainvpcCidrBlockIPv6
        - rule_number: 10200
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 6
          port_range:
            from: 1024
            to: 65535
        - rule_number: 10206
          rule_action: allow
          direction: ingress
          ipv6_cidr_block: "::/0"
          protocol: 6
          port_range:
            from: 1024
            to: 65535
        - rule_number: 10300
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 17
          port_range:
            from: 1024
            to: 65535
        - rule_number: 10306
          rule_action: allow
          direction: ingress
          ipv6_cidr_block: "::/0"
          protocol: 17
          port_range:
            from: 1024
            to: 65535
        - rule_number: 30100
          rule_action: allow
          direction: egress
          protocol: -1
          cidr_block: 0.0.0.0/0
        - rule_number: 30106
          rule_action: allow
          direction: egress
          protocol: -1
          ipv6_cidr_block: "::/0"
    - name: PrivateLinkNACL
      vpc_id: !stack_output networkhub/ec2/vpc.yaml::mainvpc
      tags:
        Name: TransitGW-NACL
        Project: {{ stack_group_config.project_code }}
      nacl_entries:
        - rule_number: 10100
          rule_action: allow
          direction: ingress
          protocol: -1
          cidr_block: 0.0.0.0/0
        - rule_number: 10106
          rule_action: allow
          direction: ingress
          protocol: -1
          ipv6_cidr_block: "::/0"
        - rule_number: 30100
          rule_action: allow
          direction: egress
          protocol: -1
          cidr_block: 0.0.0.0/0
        - rule_number: 30106
          rule_action: allow
          direction: egress
          protocol: -1
          ipv6_cidr_block: "::/0"


stack_tags:
  Name: networkhub-networkacl