template_path: ec2/security_group.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  security_groups:
    - name: NATInstanceSG
      group_description: NAT Instance
      vpc_id: !stack_output networkhub/ec2/vpc.yaml::mainvpc
      tags:
        Name: NATInstance-SG
        Project: {{ stack_group_config.project_code }}
      security_group_egress:
        - ip_protocol: -1
          description: Allow all outgoing access to Internet IPv4
          cidr_ip: 0.0.0.0/0
        - ip_protocol: -1
          description: Allow all outgoing access to Internet IPv6
          cidr_ipv6: "::/0"
      security_group_ingress:
        - ip_protocol: -1
          description: Allow all incoming from Office private subnets
          cidr_ip: {{ var.subnet_cidr_block.office.hq }}
        - ip_protocol: -1
          description: Allow all incoming from the environment range
          cidr_ip: {{ var.network_range }}

stack_tags:
  Name: networkhub-ec2-securitygroup