template_path: ec2/vpc.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  vpcs:
    - name: mainvpc
      cidr_block: {{ var.subnet_cidr_block.network_hub.vpc }}
      use_ipv6: true
      tags:
        Name: {{ var.vpc_name }}
        Project: {{ stack_group_config.project_code }}

stack_tags:
  Name: networkhub-vpc