template_path: s3/bucket.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  source_repo_branch: !environment_variable SOURCE_REPO_BRANCH
  buckets:
    - name: Test01
      access_control: Private
      bucket_encryption:
        server_side_encryption_configuration:
          - bucket_key_enabled: true
            service_side_encryption_by_default:
              sse_algorithm: AES256
      public_access_block_configuration:
        block_public_acls: true
        block_public_policy: true
        ignore_public_acls: true
        restric_public_buckets: true
      bucket_policy:
        policy_document: |
          Version: "2012-10-17"
          Id: BucketPolicy
          Statement:
            - Sid: AllowSSLRequestsOnly
              Action: "s3:*"
              Effect: Deny
              Resource:
                - !GetAtt Test01.Arn
                - !Join ['/', [!GetAtt Test01.Arn, '*']]
              Condition:
                Bool:
                  "aws:SecureTransport": false
              Principal: "*"
            - Sid: BlockDeleteBucket
              Action: "s3:DeleteBucket"
              Effect: Deny
              Resource:
                - !GetAtt Test01.Arn
              Principal:
                AWS:
                  - "*"
      tags:
        SourceRepoURL: !environment_variable SOURCE_REPO_URL


stack_tags:
  Name: demo-sceptre
