---
template_path: ec2/internet_gateway.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  internet_gateways:
    - name: demovpc
      vpc_id: !stack_output demoaccount/ec2/vpc.yaml::demovpc
      tags:
        Name: demovpc
        Project: {{ stack_group_config.project_code }}

stack_tags:
  Name: demo-sceptre