---
template_path: ec2/route_table.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  route_tables:
    - name: Public
      tags:
        Name: RTPublic
        Project: {{ stack_group_config.project_code }}
      vpc_id: !stack_output demoaccount/ec2/vpc.yaml::demovpc
      route_entries:
        - name: DefaultIPv4
          destination_cidr_block: 0.0.0.0/0
          gateway_id: !stack_output demoaccount/ec2/internetgateway.yaml::demovpc
        - name: DefaultIPv6
          destination_ipv6_cidr_block: '::/0'
          gateway_id: !stack_output demoaccount/ec2/internetgateway.yaml::demovpc
    - name: PrivateA
      tags:
        Name: RTPrivate-A
        Project: {{ stack_group_config.project_code }}
      vpc_id: !stack_output demoaccount/ec2/vpc.yaml::demovpc
    - name: PrivateB
      tags:
        Name: RTPrivate-B
        Project: {{ stack_group_config.project_code }}
      vpc_id: !stack_output demoaccount/ec2/vpc.yaml::demovpc

stack_tags:
  Name: demoaccount-route