template_path: iam/instance_profile.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  instance_profiles:
    - name: NATInstanceRole
      role_name: !stack_output networkhub/iam/role.yaml::NATInstanceRole

stack_tags:
  Name: networkhub-iam-instanceprofile