template_path: iam/role.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  roles:
    - name: NATInstanceRole
      assume_role_policy_document: |
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      description: IAM Role for NAT Instance
      managed_policy_arns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      max_session_duration: 7200
      policies:
        - policy_name: NATInstanceCustomPolicy
          policy_document: |
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - ec2:DescribeInstances
                  - ec2:CreateRoute
                  - ec2:ReplaceRoute
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:DescribeRouteTables
      tags:
        Name: NATInstanceRole
        Project: {{ stack_group_config.project_code }}

stack_tags:
  Name: networkhub-iam-role