---
template_path: ssm/parameter.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  source_repo_branch: !environment_variable SOURCE_REPO_BRANCH
  parameters:
    - name: Amazon2CwagentConfig
      parameter_name: /cwagent/amazon2/config
      type: String
      value: !file helper-templates/cwagent-amazon2-config.json.txt
    - name: WindowsCwagentConfig
      parameter_name: /cwagent/windows/config
      type: String
      value: !file helper-templates/cwagent-windows-config.json.txt

stack_tags:
  Name: sceptre-demo